name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install devkitpro
      run: wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -S 3ds-dev
          sudo pacman -S 3ds-dev

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
