name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm
      
    steps:
    - uses: actions/checkout@v4

    steps:
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "PATH=$DEVKITPRO/devkitARM/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: make
